### PR TITLE
Update solidity compiler (depends on #68)

### PR DESCRIPTION
**Pull request by dtebbs**

### CODE REVIEW

**Review by AntoineRondelet — APPROVED** [review]
Great, good to migrate to `0.8` - LGTM

**Comment by AntoineRondelet** [comment]
I think this one needs to be rebased on `develop`. @dtebbs would you mind rebasing?

**Comment by dtebbs** [comment]
Didn't catch that. Thanks @AntoineRondelet .  Should be rebased now.

**Comment by AntoineRondelet** [comment]
> Didn't catch that. Thanks @AntoineRondelet . Should be rebased now.

Perfect, thanks @dtebbs - this one is ready to go!

**Pull request merged**
